### ISSUE TITLE
Highlight prefix not boldable

### ISSUE THREAD

**Issue by laur89** [tmux-plugins/tmux-prefix-highlight#27]
How can we set the prefix highlight bold?
It used to work as

```
set -g @prefix_highlight_fg "colour239,bold"
```
but now it simply prints 'bold' out.
Looks like highlight doesn't have an attr setting as copy & sync have so how to make highlight prefix bold?

Using ver 41d4ef4
Potentially related to #26?

**Comment by smesko85** [comment]
It seems broken for me, as well :(

**Comment by dsedivec** [comment]
> How can we set the prefix highlight bold?
> It used to work as
> 
> ```
> set -g @prefix_highlight_fg "colour239,bold"
> ```
> 
> but now it simply prints 'bold' out.

@laur89, try this instead in your `tmux.conf` and let us know if it works for you, please?

```
set -g @prefix_highlight_fg "colour239#,bold"
```

I'd call that a temporary fix.  To the maintainers, I think @smesko85 might be on the right track: Does `format_style` need to be called on the `prefix_highlight_fg` and `..._bg` values?  Looks like it's being called on the other settings but not those two.

**Comment by smesko85** [comment]
@dsedivec Thank you!
I am using hex colors and I can finally set 'bold'  :)

`set -g @prefix_highlight_fg "#d9d9d9#,bold"`

**Comment by laur89** [comment]
Same here, @dsedivec recommendation works. Could you please explain why is it so?

**Comment by dsedivec** [comment]
> Same here, @dsedivec recommendation works. Could you please explain why is it so?

I believe you see "bold" in the status bar because `prefix_highlight_fg` is being interpolated into a [tmux format string][1] like `#{?cond,true,false}` and the comma before "bold" is not escaped.  Inside conditionals, if you want to include a comma in the `true` or `false` parts, that comma needs to be escaped as `#,`, per the docs.

I think tmux-prefix-highlight actually takes a different route to avoid commas inside conditionals: it tries to turn, for example, `#[fg=#d9d9d9,bold]` into (I think) `#[fg=#d9d9d9]#[bold]`, which is also valid and avoids the comma.  That transformation is being applied to other tmux-prefix-highlight settings, but just not to `prefix_highlight_fg` and `prefix_highlight_bg` anymore, and I suspect that's an oversight.

[1]: https://man7.org/linux/man-pages/man1/tmux.1.html#FORMATS

**Comment by MunifTanjim** [comment]
> That transformation is being applied to other tmux-prefix-highlight settings, but just not to `prefix_highlight_fg` and `prefix_highlight_bg` anymore, and I suspect that's an oversight.

Hmm 🤔 I introduced that transformation. I thought those two options are for only setting color (as mentioned in the README.md)

> 
> The colors used for the prefix highlight can be configured:
> 
> ```
> set -g @prefix_highlight_fg 'white' # default is 'colour231'
> set -g @prefix_highlight_bg 'blue'  # default is 'colour04'
> ```

That's why I didn't applied the transformation on those two options.

**Comment by laur89** [comment]
> That's why I didn't applied the transformation on those two options.

Not following here - what was the reason?

**Comment by MunifTanjim** [comment]
> what was the reason?

I thought those two options are for setting only color (not other attributes). Clearly, I was wrong because those are being used to apply other attributes too.

The fix would be to change this line:

https://github.com/tmux-plugins/tmux-prefix-highlight/blob/41d4ef4990d9435017a5607bbb9ee4b4eafe7b31/prefix_highlight.tmux#L67

to this:

```sh
    local -r prefix_highlight="$(format_style "fg=$fg_color,bg=$bg_color")"
```

That should work (not tested).

I don't use this plugin anymore. So if somebody wants to make a PR with this change, they're welcome.

**Comment by dsedivec** [comment]
> As I don't use this plugin anymore (I made my trimmed down version of this: [tmux-mode-indicator](https://github.com/MunifTanjim/tmux-mode-indicator)), if somebody wants to make a PR with this change, they're welcome.

Done in #29.  Thanks!
