### ISSUE TITLE
Prefix indictator doesn't show until reload

### ISSUE THREAD

**Issue by Dhamma-valence** [tmux-plugins/tmux-prefix-highlight#30]
When tmux first loads, the indicator doesn't show up when pressed. However, if I do 
```
source-file ~/.tmux.conf
```
it suddenly works.

I should mention, I am using the tmux config file at https://github.com/gpakosz/.tmux, as well as TPM, so instead of doing 
``` set -g status-right '#{prefix_highlight} ```
I have to do
``` tmux_conf_theme_prefix="#{prefix_highlight}" ```

**Comment by mickaelseznec** [comment]
Hi, I've been facing the same issue. For me, the problem was that the status option was not fetched here: 
https://github.com/tmux-plugins/tmux-prefix-highlight/blob/master/prefix_highlight.tmux#L26

Changing `local -r value=$(tmux show-option -Aqv "$1")` to `local -r value=$(tmux show-option -gqv "$1")` made it work. This has been changed in a recent commit d9e4e606c4bda822041f4ea4e5231a38bee07eec though, so I'm not sure if that applies to you also.

**Comment by wantyapps** [comment]
Worked like a charm @mickaelseznec.

**Comment by erickpintor** [comment]
Hi there. Could someone validate if #33 has fixed the problem?

**Comment by mickaelseznec** [comment]
@erickpintor it works for me now, thanks for taking care of it!
